CREATE TABLE mintaka (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    current_price NUMERIC,
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    high_24h NUMERIC,
    low_24h NUMERIC,
    price_change_24h NUMERIC,
    price_change_percentage_24h NUMERIC,
    price_change_percentage_7d NUMERIC,
    price_change_percentage_30d NUMERIC,
    price_change_percentage_24h_in_currency NUMERIC,
    price_change_percentage_7d_in_currency NUMERIC,
    price_change_percentage_30d_in_currency NUMERIC,
    market_cap_change_24h BIGINT,
    market_cap_change_percentage_24h NUMERIC,
    ath NUMERIC,
    ath_change_percentage NUMERIC,
    ath_date TIMESTAMP,
    atl NUMERIC,
    atl_change_percentage NUMERIC,
    atl_date TIMESTAMP,
    circulating_supply NUMERIC,
    total_supply NUMERIC,
    max_supply NUMERIC,
    fully_diluted_valuation BIGINT,
    last_updated TIMESTAMP,
    last_updated_at BIGINT,
    image TEXT,
    usd NUMERIC,
    usd_24h_change NUMERIC,
    usd_24h_vol NUMERIC,
    usd_market_cap NUMERIC
);